DELETE http://localhost:3003/api/blogs/65b65599ac79627e9da475cb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvaW5lbmtheXR0YWphIiwiaWQiOiI2NWI2NTU2M2FjNzk2MjdlOWRhNDc1YzMiLCJpYXQiOjE3MDY0NTAzMTMsImV4cCI6MTcwNjQ1MzkxM30.xtDMGaA9M_3g6kFwLqh-WhOtJZk2hakl7lYM7E9N2BA