DELETE http://localhost:3003/api/blogs/65b66b4797f6674118c98be3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhYWtheXR0YWphIiwiaWQiOiI2NWI2NGRlOWE5ZWI1NjY2YzY4NmI2NzkiLCJpYXQiOjE3MDY0NTM4ODcsImV4cCI6MTcwNjQ1NzQ4N30.jGmhe0_0_yOqVayw2JIoM8iQHZewOyrVSGLypmAJZtM